name: Plugin compatibility request
description: Request support for a specific plugin or plugin version
title: "[COMPAT]:"
labels: ["Compatibility", "Priority: Optional"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this compatibility request!
  - type: input
    id: server-software
    attributes:
      label: Server Software
      description: The software that you are using to run the server.
      placeholder: "Spigot"
    validations:
      required: false
  - type: input
    id: minecraft-version
    attributes:
      label: Minecraft Version
      description: The version of Minecraft that you are using.
      placeholder: "1.18.2"
    validations:
      required: false
  - type: input
    id: plugin-name
    attributes:
      label: Plugin Name
      description: The name of the plugin that you want compatibility for.
    validations:
      required: true
  - type: input
    id: plugin-version
    attributes:
      label: Plugin Version
      description: The version of the plugin that you want compatibility for.
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Why should we add compatibility for this plugin with that version?
      description: A clear and concise description of why we should support that plugin with that version.
    validations:
      required: true
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Any additional information that you would like to share.